### ISSUE TITLE
5M240ZT100C5 and other C5 timing requirements

### ISSUE THREAD

**Issue by sftwninja** [borti4938/n64rgb#1]
Hey, I noticed in the documentation, it's noted that the 5M240ZT100C5 / 5M570ZT100C5 don't meet the timing requirements needed by RGB. What timing requirements exactly are needed? I'm looking into expanding upon this using a MAX 10 series C7 (like a 10M02DCV36I7G) for some additional uses that would be helpful, but it would be helpful to know what kind of timings are absolutely necessary.

Thanks, and this project has been a blast to read through.

**Comment by borti4938** [comment]
Hey,
you can use the SDC files for timing requirements. They are provided with the firmware files:

- [n64rgb.sdc](https://github.com/borti4938/n64rgb/blob/master/generalRGBmod/firmware/n64rgb.sdc) defines the clocks for video processing
- [n64igr.sdc](https://github.com/borti4938/n64rgb/blob/master/generalRGBmod/firmware/n64igr.sdc) defines the clocks for IGR processing

I will add this information to the read me ;)

Max10 is a next step for me, too. A Max10 FPGA would allow linedoubling, which would be the next consequential step.
However, I want to have a simple on screen feedback for the 570LEs CPLDs if the user changes some settings with the controller, first.

**Comment by sftwninja** [comment]
Thanks for the swift response!

That's exactly what I needed to look at. For some reason my eyes completely glazed over at the sdc's (just completely missed them). Thanks for the super clean codebase :D It really has been a joy to step through.

**Comment by sftwninja** [comment]
And yes I'd love to collaborate on this :D 
I plan on adding a few non-RGB functionality for personal niceities, but the changes that directly affect this will definitely get upstreamed, besides work that needs to be done in general.

**Comment by borti4938** [comment]
thanks for the words :) I'm looking forward to new ideas.
I now added the discussed information to the read me as well as my ideas.

BTW: At the moment I do have the 10M2SCE144C8G at home for testing but still no prototype PCB for that. But this will come during summer :D

**Comment by sftwninja** [comment]
Awesome :D 
Is there a way I can get a hold of you or a discord or something? I'd like to chat with you sometime if you have the time and seek out some advice from someone with a lot more experience. :)

**Comment by borti4938** [comment]
I have a Skype account but haven't used it since years *whoo*... Maybe I have to reactivate it as well as my Twitter account :P
Meanwhile write me an email such that I can write you my contacts once I found my account credentials.
