### ISSUE TITLE
Missing color depth with Cyclone IV - N64 Advanced

### ISSUE THREAD

**Issue by Arthrimus** [borti4938/n64rgb#10]
I have been trying to get a couple of the N64 Advanced boards up and running with Cyclone IV ep4ce10e22 and I'm having an issue where I seem to be missing quite a bit of color depth from the FPGA to the dac. From what I can tell I am missing most of the blue color spectrum and possibly some of the red as well. I've tested these same PCBs with a Cyclone 10 and it's respective firmware and everything is working as expected. It's only with the Cyclone IV and firmware that I am having this problem. Any ideas? Thanks.

**Comment by borti4938** [comment]
My current deelopment console is based on the Cyclone IV variant. So I cannot say, what is wrong. Do you have some pictures and situations where I probably can reproduce it?

**Comment by borti4938** [comment]
Any progress here?
