### ISSUE TITLE
Clarification for the Component Output and VGA Cables

### ISSUE THREAD

**Issue by Helder1981** [borti4938/n64rgb#12]
I am trying to use the Component output but am getting some weird issues and I have set the jumpers J33 and on the Flex PCB for the Filter to the 75ohm Csync not the TTL sync jumper. I made my own cable and it has the 220uf caps in line with the 3 color lines as per the PDF and I also tied sync to the Y cinch.

Now the issue is that there is some ghosting of the entire image BUT when the OSD menu is present the ghosting is gone where the menu is shown. Pictures below:
![20200923_131931](https://user-images.githubusercontent.com/8185885/94053419-ef060d00-fd9f-11ea-8b72-c2f5c80c5c80.jpg)
![20200923_132002](https://user-images.githubusercontent.com/8185885/94053422-ef9ea380-fd9f-11ea-907d-45ffe3469978.jpg)

So my question is how to make the Component output properly, was it intended to not use the flex pcb with filter and just wired up to the AV pin directly from the N64Advance?

For the VGA output I need to set J1.2 and wire directly from the PCB output pads skipping the Filter Flex PCB and AV pins correct? Or is there something else that needs to be done to get that to work properly as well?

Thank you and the updated info for compiling the firmware has helped from your previous closed Issue.

**Comment by borti4938** [comment]
> I am trying to use the Component output but am getting some weird issues and I have set the jumpers J33 and on the Flex PCB for the Filter to the 75ohm Csync not the TTL sync jumper. I made my own cable and it has the 220uf caps in line with the 3 color lines as per the PDF and I also tied sync to the Y cinch.

Whooo... stop! Sorry, maybe these are my English skills... Not sure what you exactly did. Did you connect separate sync and Y together for the cinch cable? Do I understand that right?
If so, this is not correct by no means! Sync comes together with the Y-component and does not have to be added 'by hand' like you did.

Seperate sync has no influence on YPbPr output as it is not used at all. So J33 and also sync routing on the flex board is totally irrelevant in this mode.

>So my question is how to make the Component output properly, was it intended to not use the flex pcb with filter and just wired up to the AV pin directly from the N64Advance?

As described. Just connect Y, Pb and Pr output of the multiout (you are stucked to pin 2, 4 and 1 of the multiout, respectively, if you use the flex cable)  with some cinch plugs. Using 220uF caps (+ to multiout, - facing cinch ends) is **optional**; not really needed, not harmful to video quality in my eyes.

Flex PCB works 100% fine with Component output in either configuration (without or with filter).

> For the VGA output I need to set J1.2 and wire directly from the PCB output pads skipping the Filter Flex PCB and AV pins correct? Or is there something else that needs to be done to get that to work properly as well?

VGA output is not compatible with the filter addon. At least not with additional modifications.

**Comment by Helder1981** [comment]
Yes I removed that Luma and the image is stable now and even line doubles and triples on my LCD TV. Thank you. The confusion came from other Component mods where Sync is tied to the output Y and this is not needed here.

Are you a part of some Discord or frequent a forum that is mostly in English? I'd love to talk to you about improving this mod further.
