### ISSUE TITLE
Cyclone 10 No Menu after Firmware Update

### ISSUE THREAD

**Issue by Slypty** [borti4938/n64rgb#15]
I just installed the newer (Jan 9th release) on Cyclone 10.  Although the Mod works (Tested OK for RGB output) I cannot access the Menu with the normal button keys (Right D-Pad, with L1 and R1 & Ri button combination)
Firmware Progress shows 100% Success with no errors.
 No Menu boots when the Console is powered on

**Comment by borti4938** [comment]
It would be very polite to share the cause of the issue. There was nothing changed with menu behaviour.
Btw: you can always go back using the Github history.

**Comment by Slypty** [comment]
Thanks for the History tip, I will try another firrmware.

  I haven't figured out the issue, I will share as soon as it is solved.
This board I made myself, would any component failure or bad contact cause
this issue?  Continuity from middle controller pin to CTRL on the Board is
OK.  It is the C8G Cyclone 10 Version.
Here is a copy of the Quartus Programmer messages during Programming, does
it look right?
Info (209060): Started Programmer operation at Mon Jan 25 18:35:45 2021
Info (209016): Configuring device index 1
Info (209017): Device 1 contains JTAG ID code 0x020F10DD
Info (209007): Configuration succeeded -- 1 device(s) configured
Info (209018): Device 1 silicon ID is 0x14
Info (209044): Erasing ASP configuration device(s)
Info (209023): Programming device(s)
Info (209021): Performing CRC verification on device(s)
Info (209011): Successfully performed operation(s)
Info (209061): Ended Programmer operation at Mon Jan 25 18:35:52 2021

Other possibilities?
 I started the game with out the transfer pak by mistake on the first run
after programming the firmware.  I hope I did not corrupt the FPGA.  The
RGB works on OSSC well, but no Menu shows.
- FPGA output pins for Menu, any way to check these connections?  Sorry
maybe too specific to ask, just wondering.  Thanks

**Comment by borti4938** [comment]
Try to reflow U8. If it is not correctly soldered, the Soft-CPU has no clock and cannot run. Do you get any other response from the CPU, e.g. correctly loaded jumper when coming from earlier firmwares or entering fallback (linex2 disabled) when booting with reset button pressed?

The FPGA does not have 'menu-specific' pins. It's injected into video data. Other pins to look at could be:
- pin 24 (clock input from U8)
- pin 127 (controller input)

**Comment by Slypty** [comment]
Thank you, I know the Clock orientation but this time I made an error.  I
put the Clock upside down.  The Clock writing is so small I may have read
it incorrectly.
Your help is greatly appreciated, it would have taken me so long to figure
out the problem.

 D you have any recommendations to go from VGA to HDMI?  The adapters I try
do not output the same image as VGA.    Cheers
