### ISSUE TITLE
Are there videos on soldering the pad under the ic?

### ISSUE THREAD

**Issue by ryanbuyandsellgames** [borti4938/n64rgb#18]
The surface mount stuff is no problem at all I've done that before but I've never done soldering under a chip.

Is it done with a heat gun?

Anyone have any good tutorials?

 exposed pad below the IC, which has to be soldered to

**Comment by borti4938** [comment]
Sorry for the  late reply. Wasn't logged in for a while.

There are not special tools requiered. Although heat gun might be helpful, it is possible to assemble the board without. It's made for DIY, which e.g. means for the exposed pad of the FPGA that there is a large via below. In that way you can solder the exp pad after once you finished the pins.
