### ISSUE TITLE
IGR automatically being activated v1

### ISSUE THREAD

**Issue by networkingyuppy** [borti4938/n64rgb#3]
Hi there I have a 240 max v chip and flashed the firmware on it with the controller signal wired up to pin 16 and reset wired up to pin 28. It seems like the controller is automatically activating the reset when both of these wired are connected to Ctrl and rst on the board

**Comment by borti4938** [comment]
What was the problem - just curious. It also helps other people avoiding the same mistake in case it was one. And it also helps me if the documentation was not clear enough at a certain point. ;)
