### ISSUE TITLE
IGR with viletim's board isn't working

### ISSUE THREAD

**Issue by Quantum-cross** [borti4938/n64rgb#4]
I've programmed to `n64rgb_viletim_igr.pof` tim's N64RGB board and I can't seem to get IGR working at all.

I have the middle pin of the controller port connected to pad `A` (from directly under the controller port). I also have the reset switch connected properly I believe. I forget which pin I used but pad `M` is pulled to ground when I physically press the reset switch.

I've tried switching on/off de-blur with the default combinations and I see no change. The system does not reset when using the reset combination.

Any ideas?

**Comment by Quantum-cross** [comment]
It's a super pain in the butt to get under the motherboard, but I'd rather not unless absolutely necessary. The important one is the controller pin, right? I tested it with my multimeter to make sure.

Now I just ran another test. I left pad `A` open and connected pad `M` to a switch to `GND`. When I hit the switch I can clearly see the de-blur on my capture setup.

If this were truly the IGR firmware, wouldn't pad M be an output?

Could the `_sw` and `_igr` files have gotten mixed? I am 100% sure I flashed `_igr`.

**Comment by Quantum-cross** [comment]
If I install `_sw` I get no video output with pads `A` and `M` open, but I still get audio.

**Comment by borti4938** [comment]
Files are named automatically by Quartus Prime. Related top file and *.pin-file also show that it's correct. I also have re run synthesis, fitter and assembler. The result is (except for header due to Quartus Prime update) the same.

- Which game have you tested?  
(Depending on game the deblur algorithm may struggle between on/off)
- Can you share pictures of your installation?
- Which button combination set have you used?

**Comment by Quantum-cross** [comment]
* Mario kart, mischief makers

* I'll pull off the heatsink and post some pics when I get home tonight

* I flashed `n64rgb/generalRGBmod/firmware/output_files/viletim/n64rgb_viletim_igr.pof`, wouldn't that get me the default C le + L + R + D le and C ri + L + R + D ri?

**Comment by borti4938** [comment]
Mario Kart should have a stable estimation (VI deblur on). Maybe you have a cold solder joint here on the MSBs (bit 6 and 5). For mischief makers I don't know that.

The button combination are old style and outdated since a long time. Here is the [current set](https://github.com/borti4938/n64rgb/blob/master/generalRGBmod/firmware/vh/igr_params.vh#L73)

**Comment by Quantum-cross** [comment]
Oi, I didn't know the button combos were changed. The old ones are all over the documentation. I'll reflash it and try again tonight.

If I had a cold joint on those bits wouldn't my picture look terrible?

**Comment by borti4938** [comment]
Apparently I forgot to changed the description. I'm sorry for that confusion.
Bugfix committed immediately: ed3c23408a910fed05b8e7e59d5f4a1e5683ca29

**Comment by Quantum-cross** [comment]
Ok, so the IGR combos are working but I'm getting some weird diagonal artifacting, it's quite pronounced in mario 64.

Here are install pics: https://imgur.com/a/y3Tcq

I will try and take some pictures or video of the artifacting.

**Comment by Quantum-cross** [comment]
Nevermind, it turns out the artifacts are present even in composite video... and even in some random youtube video I've found? What's up with the blinking pixels in the background on "MARIO"???

Anyway, thanks so much for your help borti, and thank you for this project. Everything seems to be in order!

While I have your attention, will viletim's board be capable of producing the OSD that you are working on?

**Comment by borti4938** [comment]
You probably have picture noise as your digital wires passing the MultiOut quite closely. The signals couple into the analog output there. Try to increase distance here.
Here is how my installation looks like: https://twitter.com/borti4938/status/956983067444482048

The CPLD does not offer resources for an OSD menu implementation.

**Comment by Quantum-cross** [comment]
That's a good idea, I will make those changes. Thanks again!
