### ISSUE TITLE
No Signal using Deinterlacer, LineMultiplier with latest firmware

### ISSUE THREAD

**Issue by alexhemard** [borti4938/n64rgb#5]
I just built and installed a N64 Advanced board with the latest firmware on `master`. The deblur and 15-bit color modes were working correctly, but when I tried to use deinterlacing or line multiplying, the signal would cut out.  Using the firmware from this commit https://github.com/borti4938/n64rgb/commit/fe5626248b9802c28787e304e53cc7e6fe50f41e - the line doubling and de interlacing works correctly. Not sure if this is a problem with my install or a regression with the 720p updates - any suggestions would be appreciated! I'm using a PVM-20L5 with 75ohm csync connected to pin 3 of the multi out and the FPGA is the Cyclone 10 FPGA (10CL010YE144C8G)

**Comment by borti4938** [comment]
I guess, you don't use the [flex adapter](https://github.com/borti4938/n64rgb/tree/master/misc/RCP2Pads) in your installation, right?
Actually your problem is that the video pll does not lock due to inproper signal cleanliness on VCLK.
With introducing the LineX3 mode I started to use (again) a PLL for video clock genearation. There are a few installation (and picky FPGAs) who do not like to have "simple" installation without resistors at the RCP-NUS output. Some suggested solutions:
- try thinner wires
- try a ferrit around the connection wires between N64 and modding board
- install the [flex adapter](https://github.com/borti4938/n64rgb/tree/master/misc/RCP2Pads) (don't forget to replace the resistor arrays RN10-12 on the N64Adv board with ferrit arrays

At the moment I don't have the time to implement a backup solution at least for LineX2 and deinterlacing mode if the video PLL does not lock.

**Comment by alexhemard** [comment]
I'm currently using the flex adapter (with ferrite array on the N64A, resistors on adapter). I was using a ribbon cable to connect D0-7, DSYNC, VCLK to the board. I've tried removing DSYNC, VCLK from the ribbon cable and using shorter, separate 28AWG wires for those lines and still no sync with de-interlace or line multiplying modes. I'll report if a ferrite clamp on the lines improves things and  continue to use the older firmware in the meantime :) thanks!

**Comment by borti4938** [comment]
OK, first time I heard about this problem while using the flex cable. Can you share a picture from your installation?

Please also try thinner wires, shortening of wires and/or more (and thicker) GND wires

**Comment by alexhemard** [comment]
> Please also try thinner wires, shortening of wires and/or more (and thicker) GND wires

I'll try and source a some better/thinner ribbon cable - Do you have a recommended wire size?

Here's my current installation: 
![IMG_7275](https://user-images.githubusercontent.com/891125/62878093-06924b80-bcee-11e9-96cd-b77ccb905468.jpg)
![IMG_7271](https://user-images.githubusercontent.com/891125/62878094-06924b80-bcee-11e9-9b04-844b95c78351.jpg)

**Comment by borti4938** [comment]
Sorry for the late response.
Actually I don't know how thin my wires are. Maybe 0.15mm^2 or 0.22^2?
However, I worked on the firmware for having the video PLL only as an option. Would you like to try? If so, just send me an email.

**Comment by borti4938** [comment]
Hey,
do you still have this issue? If so, I would love to send you a flex cable to see if this resolves your issue?
Best Regards,
Peter

**Comment by JeromeMarousez** [comment]
Since I now have a Github account, I can share my findings as I'm in PAL territory. The latest firmware (at least the one that was flashed back in June/July) seems to have fixed some of it. Line 2x doesn't work on my old 1080p Samsung but does work on the OSSC. I was using the flex cable.

**Comment by borti4938** [comment]
Which kind of flex cable do you use. If you use the flex shown in your youtube video (other thread), then this really might be an issue. I can recommend the newer one with line buffers for data and clock lines.

VI-deblur estimation is removed in current firmware as I found more and more situations where actual implementation won't estimate reliable if deblur is usable or not. But you will have the opportunity to maunally turn it on and off.

**Comment by JeromeMarousez** [comment]
Yes, regarding Deblur turning itself off (for 1 second only), it was just to let you know and have a reliable way to test it for yourself - if needed - as it always happens at the same moment.

I was using the small flex cable. I haven't have the opportunity to install the long flex cable.

**Comment by borti4938** [comment]
VI-Deblur stuff with unreliable auto detection goes here: https://github.com/borti4938/n64rgb/issues/11
