### ISSUE TITLE
Can't load firmware - advice needed

### ISSUE THREAD

**Issue by toto99303** [borti4938/n64rgb#6]
Hello borti4938,

I've assembled a small batch of 5 N64 RGB advanced boards, but I'm having trouble loading the firmware on them. I have a brand new Terasic USB Blaster and every time I try loading it fails. I also tried another USB-Blaster that I have also wothout success, so the interface is not the problem. The board is powered with 3.3V and I also measured it. I'm using Cyclone 10 on the board. I tried on my Windows 10, and tried also on Windows 7 without success. Can you point me to the right direction how to troubleshoot the problem?
![1](https://user-images.githubusercontent.com/20519170/83609867-7fb5a480-a587-11ea-854a-1a43badb3038.jpg)
![2](https://user-images.githubusercontent.com/20519170/83609873-804e3b00-a587-11ea-97f7-ff06e8e674d3.jpg)
![3](https://user-images.githubusercontent.com/20519170/83609874-80e6d180-a587-11ea-80eb-e1669c7e2fbc.jpg)

**Comment by borti4938** [comment]
Check if FPGA is correctly soldered: power supply pins, GND pins, exposed pad and JTAG pins.

**Comment by toto99303** [comment]
Re-soldered the bottom GND pad and it worked like charm. Thanks!

**Comment by Helder1981** [comment]
I have a different issue on every version of the programming software I get this error if it's in JTAG mode, in other modes it seems to load without the error. If I load the .sof file in JTAG mode it gives me no error. any idea how to fix this? Using an Altera Blaster clone.
![Screenshot 2020-08-14 12 40 12](https://user-images.githubusercontent.com/8185885/90277664-a287f300-de2b-11ea-9cea-e04c90eb2287.png)

**Comment by borti4938** [comment]
For programming the firmware when the modboard is installed, you have to use the JIC-file. The flash device is then automatically added to the JTAG chain besides the FPGA.
The flash will be programmed using a special FPGA configuration then. So you have to power cycle the console once successfully done. (or you reconfigure the FPGA using the SOF-file afterwards).
